### ISSUE TITLE
Add "Folder Download" support

### ISSUE THREAD

**Issue by askfriends** [cheems/goindex-extended#17]
Can you add Folder Download support? It will be a great option.

**Comment by askfriends** [comment]
> This index completely works using Google Drive API but with the API, there is no direct way to export a folder as a zip or some kind of archive. Therefore it is practically not possible at the current stage.
> 
> But the object can be achieved using a program which can download files within a folder recursively maintaining the folder structure. Since I couldn't find one which can do the task, I started writing a python package which can download folders from Google Drive Index sites. But it is still under development.
> 
> Since I'm packed with the daily routine at the moment, It may take some time to make it available for public use.

Thanks for the explanation and yeah that would be nice, Can you send that link when its ready to use?

**Comment by onmgmedina** [comment]
Any update on this?

> This index completely works using Google Drive API but with the API, there is no direct way to export a folder as a zip or some kind of archive. Therefore it is practically not possible at the current stage.
> 
> But the object can be achieved using a program which can download files within a folder recursively maintaining the folder structure. Since I couldn't find one which can do the task, I started writing a python package which can download folders from Google Drive Index sites. But it is still under development.
> 
> Since I'm packed with the daily routine at the moment, It may take some time to make it available for public use.
