### ISSUE TITLE
readme.md is kinda broke

### ISSUE THREAD

**Issue by AmirulAndalib** [cheems/goindex-extended#18]
![Screenshot (3218)](https://user-images.githubusercontent.com/86344856/135759226-9201e804-5777-4be6-be87-d661b129337d.png)

it used to work fine on Bhadoos Index but now i am seeing this broke any fixes or suggestions?

`<h2>Hola Peepz Welcome to Google Drive Index By MirrorLeech 🙈</h2> <h2>Have Fun😀👋</h2>`

`<div align="center">`

`<h1>Presenting a Google Drive Index By Amirul Andalib</h1>`

`<a href="https://mirrorleech.ml/0:/BotUploads/" target="_blank"><img src="https://shields.io/badge/%F0%9F%97%83-ALL--FILES--HERE%F0%9F%92%BD-blue?logo=&style=for-the-badge" alt="MirrorLeech" style="width: 400px; height:;" width="400" height="" /></a></h1>`

`<a href="https://t.me/MirroLeech" target="_blank"><img src="https://img.shields.io/badge/Telegram-Join%20Telegram%20Group-blue.svg?logo=telegram" alt="MirrorLeech" style="width: 400px; height:;" width="400" height="" /></a></h1> <div align="center">`

**Comment by cheems** [comment]
I will have a look. Until then, could you update me checking what happens if you use markdown instead of html in the markdown files

**Comment by cheems** [comment]
Fixed!

Please use the latest [index.js](https://github.com/cheems/goindex-extended/blob/master/index.js) file.
