### ISSUE TITLE
#feature_request 

### ISSUE THREAD

**Issue by sp003** [cheems/goindex-extended#19]
Global search option ( Search from all td & my drive ) , Also parsing all files by their index links directly. So don't have to depend on google login .

**Comment by cheems** [comment]
I already did some tests.

Making the search function able to search across all drives is quite easy but once the search results are retrieved, file path should be created to the file, relative to the disk root. 

In this case, if the file that user tries to download is from another drive which is not included in the index, then a download url(a path which starts from the index root (ex: blahblah.workers.dev/path/file.txt)) cannot be created.

But I still see some possibility to retrieve search results only from drives which are included in the index. But I have to study more about it before saying whether it can be done or not.
