### ISSUE TITLE
README issue

### ISSUE THREAD

**Issue by james131989** [cheems/goindex-extended#36]
Index works fine without README or HEAD
after adding both or either one of them, it keeps loading and doesnt work
it was fine few days ago
plz fix it

**Comment by cheems** [comment]
If it doesn't contain any sensitive data, could you share the link to the index(live version)?

and also, please provide me the worker code without these(any sensitive) values: [client_id, client_secret,  refresh token, crypt password, and root ids] 

I just want to review your settings. You can use https://gist.github.com to share your worker code

**Comment by xkoti** [comment]
I think the issue is when navigating to **_root /0:/_**  the site now, It will stuck on loading It wont load, also rendering of HEAD & README, It doesn't work now.

V1.4.0

**Comment by cheems** [comment]
Fixed!

Please use the latest [index.js](https://github.com/cheems/goindex-extended/blob/master/index.js) file.

The problem was occurred due to the changes in the library used for rendering markdown: https://github.com/markedjs/marked/releases/tag/v4.0.0

**Comment by xkoti** [comment]
> Fixed!
> 
> Please use the latest [index.js](https://github.com/cheems/goindex-extended/blob/master/index.js) file.
> 
> The problem was occurred due to the changes in the library used for rendering markdown: https://github.com/markedjs/marked/releases/tag/v4.0.0

I tested it in v1.4.1 and its fixed.
@cheems could you please **add icons** to todo list 😁
