### ISSUE TITLE
Order list by not working.

### ISSUE THREAD

**Issue by ZeroCool22** [cheems/goindex-extended#38]
![Screenshot_7](https://user-images.githubusercontent.com/13344308/140647576-bb765d4f-1d65-4a4f-9333-0320560248e5.png)

When I click any of this, it doesn't change the order list.

**Comment by cheems** [comment]
You can set it from here: [Line 58](https://github.com/cheems/goindex-extended/blob/48dd3e2ef73f3b1eaa8c883483215f5c62a5124c/index.js#L58)

Changing the order from the front end may cause errors even it can be implemented. Suppose one folder contains a number of files that is greater than the value you set to `files_list_page_size` ([Line 69](https://github.com/cheems/goindex-extended/blob/48dd3e2ef73f3b1eaa8c883483215f5c62a5124c/index.js#L69)), then it may cause issues. Therefore it is always better to hardcode that option.

And also I have already done several experiments regarding this to check the possibility of changing the order from the front end but couldn't get successful results(when having a number of files greater than the value set to the previously mentioned parameter). However, it is still on the to-do list(the list in the readme is not completed), and will try to do something regarding that later.

**Comment by ZeroCool22** [comment]
Alright, thank you for the information!
