### ISSUE TITLE
Failed to get the target path

### ISSUE THREAD

**Issue by pulpyboy0130** [cheems/goindex-extended#44]
![Untitled](https://user-images.githubusercontent.com/77887806/142725800-fb4b5ca8-ef22-47fc-b495-fff1ccf2416d.jpg)
Every time getting this error when searched file/folder open'
**Failed to get the target path**
It may be because this item does not exist in the Folder! It may also be because the file [Shared with me] has not been added to Personal Drive!

**Comment by cheems** [comment]
Does this happen only with this file or multiple files? Could you provide me the index link and the file you get this error? Then I can have a look. Also, provide me a screenshot of the folder location in Google Drive (not index)(Only if it doesn't contain any sensitive data).

**Comment by pulpyboy0130** [comment]
Every searched file or folder getting same error. Index - https://arkmedia.ga/ 
![Untitled](https://user-images.githubusercontent.com/77887806/142800129-806f8414-edd4-4812-85dd-15c18be16123.png)

**Comment by xkoti** [comment]
I checked this on my index and it also occurs, is [Configure Search Functionality for Folders](https://github.com/cheems/goindex-extended#-configure-search-functionality-for-folders) mandatory?

@cheems maybe change the **WTF ???** to **Ok** also? 😂😂😂

**Comment by cheems** [comment]
@pulpyboy0130 I tried again the current version (v1.4.1) and its search function works as expected. You can add me(colabdude775@gmail.com) to your shared drive as a viewer(if it is a shared drive) so I can try myself and check for logs to see what happens behind. And also I want to know with which root type you experienced this issue. Is this index drive a folder or a shared drive?

@xkoti If you don't have any folder ids in the roots section, you don't need it.

**Comment by pulpyboy0130** [comment]
I added your id to my shared drive. thanks lot for support.

**Comment by cheems** [comment]
Tried with the latest version of the index code (v1.4.1) and got no issue: https://dev.misty-poetry-0287.dudoo.workers.dev/0:search?q=dext
Also works with custom domains.

I doubt that if you entered your crypt password incorrectly. Give it a try with the sample crypt password: `1234567890123456abcdefghIJKLMN!*`

**Comment by pulpyboy0130** [comment]
Thanks lot, It's working perfectly now. You are awesome bro..... 😂😂
