### ISSUE TITLE
Important question about link Drive protection.

### ISSUE THREAD

**Issue by ZeroCool22** [cheems/goindex-extended#52]
Let's say i share a Drive link using the Worker, ppl will **not be able to report** my Drive link because it's hided behind the worker one, it's correct?

I'm asking because i'm tired of the Shared Drives getting deleted **_(the ones you can generate in some webs)_**, so i'm thinking on just using my own one, i have in my Workspace Sub. but want to be sure if my account will not be in danger if i use Worker to **hide the real Drive link**.

I know CF maybe could delete my account, but in that case i just make a new one.

**PD:** For what i read this repo have a feature so ppl can't spoof the original Drive link.
![Screenshot_3](https://user-images.githubusercontent.com/13344308/146666115-2bb951fa-149d-4d9e-acc4-3d6b4a40121a.png)

**Comment by cheems** [comment]
Here you go --> #24
