### ISSUE TITLE
The procedure isn't detailed enough

### ISSUE THREAD

**Issue by sujalgoel** [cheems/goindex-extended#57]
There is no mention of the application type.

![image](https://user-images.githubusercontent.com/67121014/148543956-05f470cf-5521-4814-9b52-cfaf09010ce6.png)

**Comment by sujalgoel** [comment]
also their is no other UI option
![image](https://user-images.githubusercontent.com/67121014/148547418-358ae79e-1685-43e8-b1c0-79bc5568afaf.png)

**Comment by cheems** [comment]
Recently, Google made some changes in Google APIs and it seems to be the method I have used to generate the refresh token is now deprecated. Please search on YouTube how to do this. But make sure to find a tutorial which is uploaded very recently. Let YT search filters select only the most recent videos for you.

You can also follow this URL: https://www.youtube.com/results?search_query=get+refresh+token+google+api&sp=EgIIBQ%253D%253D

I was unable to push any updates on this repo for a long while but I will update the docs when I get some free time

**Comment by theshivamsharma-code** [comment]
Ok
