### ISSUE TITLE
[PROBLEM] Failed to get the target path

### ISSUE THREAD

**Issue by Shirishx01** [cheems/goindex-extended#58]
Hi cheems,
I am using the latest version which is Version: 1.4.1 and I'm facing the following issue:

The search works but when I click on the searched content it says:

Failed to get the target path
It may be because this item does not exist in the Folder! It may also be because the file [Shared with me] has not been added to Personal Drive!
![image](https://user-images.githubusercontent.com/81070901/152635987-acd40e75-9f16-49d0-9e73-c7c159b3de3e.png)

I have also tried to do the "Configure Search Functionality for Folders" but when I do that it says:

[No FOLDER root type Found]
Dude, you don't need to run this if you didn't add any folder to index!
![image](https://user-images.githubusercontent.com/81070901/152636119-8700e5d3-c79b-4fb5-9447-9fbff51c5615.png)

Please tell me if there's an solution for it!

**Comment by cheems** [comment]
I think this happens because of a bad crypt_secret. Please try with the given example and let me know if it helped.

Also check this out: #44
